# Generated by Django 5.0.4 on 2024-04-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, upload_to='jobs_img/%Y/%m/%d/'),
        ),
    ]
